version: '3'
services:
  mongodb:
    image: mongo
    container_name: mongodb
    restart: always
    env_file:
      - ./.env

    ports:
      - '27017:27017'
    volumes:
      - mongodb:/data/db
  

  redis:
    image: redis
    container_name: redis
    ports:
      - '6379:6379'
    volumes:
      - redisDB:/data
      - ./redis.conf:/usr/local/etc/redis/redis.conf
volumes:
  mongodb:
  redisDB: